### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [2]:
def slice(string, index1, index2):
    return string[index1:index2], len(string)
string, len = slice("RESULTS", 2, 5)
print(string, len)

SUL 7


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [3]:
#Declare the function
def sum(num1, num2):
    return num1 + num2

#Call with the values 1 and two
res = sum(1, 2.1)

#Check the type of the result
print(type(res))

<class 'float'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [4]:
def chr_frq(string):
    dict1 = {x: string.count(x) for x in string}
    return dict1

print(chr_frq("test"))

{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [4]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])


ImportError: cannot import name 'print_orl' from 'lib' (unknown location)

In [5]:
a = [1, 2, 3]
b = [1, 2 ,3]
for i,j in zip(a, b[::-1]):
    print(i,j)

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [6]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(f"a = {a}\nb = {b}")

#concatenate horizontally
output = np.hstack((a,b))
print(f"output = {output}")




a = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
output = [[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [1]:
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))
#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
c=np.repeat(a,3)
output1=np.hstack((c,a,a,a))
print(f"output1 = {output1}")

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])

e=a+b[0][0]
f1=np.vstack((e,e,e))
f2=np.vstack((e,e,e))
f3=np.vstack((e,e,e))
output2=np.array((f1,f2,f3))
print(f"output2 = {output2}")
#print(f"output2 = {output2}")

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
g1=np.hstack((b[0][0],b[0][0],b[0][0]))
g2=np.hstack((b[0][0],b[0][0],b[0][0]))
g3=np.hstack((b[0][0],b[0][0],b[0][0]))
output3=np.vstack((g1,g2,g3))
print(f"ouput3 = {output3}")


output1 = [0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]
output2 = [[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
ouput3 = [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
